eslint/generator-eslint

- plugin/index.js
Checkbox is mostly used of multiple choice answers. I think confirm is more appropriate in this case. I also added defaults (yes for rules, no for processors).
> Fix: Change checkbox to commit for plugin generator (fixes #9)

- plugin/templates/_package.json
Generating a plugin, `yo eslint:plugin`, and then generating a rule, `yo eslint:rule`, would result in false-positive passing test suite, because the `npm test` script of `mocha` would not run any tests.
This changes the script from `mocha` to `mocha tests --recursive` to run any tests in the `tests` directory.
Fixes #25
> Fix: npm test script on plugin generator

- plugin/templates/_package.json
Updated the eslint dependency to 2.6.0 (latest) in the package.json template for `yo eslint:plugin`.
> Fix: Update eslint dep in generated package.json (fixes #14)

- .travis.yml
- package.json
- plugin/index.js
- rule/index.js
- test/test-creation.js
Updated all of generator-eslint's dependencies and fixed the deprecation warnings those updates produced. Updated .travis.yml to run tests in more Node versions (0.12, 4, 5).
> Upgrade: Update dependencies, fix deprecation warnings (fixes #17)

- app/index.js
- package.json
- test/test-main.js
**What issue does this pull request address?**
#31 (lack of app generator, so users cannot run `yo eslint`)
**What changes did you make? (Give an overview)**
Created a new main generator class (`app/index.js` by convention). This generator asks one question (rule or plugin?) and then uses `.composeWith()` to delegate to the correct sub-generator.
**Is there anything you'd like reviewers to focus on?**
The testing approach had to be a bit different due to having to mock the `.composeWith()` call. Unfortunately it's not intuitive (even sboudrias admitted as much on Stack Overflow), and I had to make further changes. I added a couple of longer comments trying to explain it, but please let me know if I can improve it further (or if you know of a better way to do this test).
Also, I added the …
> New: Main generator (calls existing generators) (fixes #31)

- plugin/templates/_package.json
- rule/templates/_rule.js
- rule/templates/_test.js
- test/test-creation.js
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[x] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
See #42.
**Please check each item to ensure your pull request is ready:**
- **n/a** I've updated documentation for my change (if appropriate)
**What changes did you make? (Give an overview)**
Throughout the generated file templates, we have used `<%= someVar %>` to interpolate …
> Fix: Double quotes correctly escaped in JS/JSON files (fixes #42)

- package.json
- tests/plugin/index.js
- tests/rule/index.js
Adding single quote pathological tests as well (although those aren't actually pathological for us, I just wanted to have coverage for weird input).
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] Add something to the core
[x] Other, please explain: The "bugfix" isn't user-facing, it just got in the way of writing good generator tests.
See issue #44.
**What changes did you make? (Give an overview)**
Added require-uncached to devDependencies and used it in plugin/rule tests to avoid `require()` cache problems. Also improved tests and added some new tests.
**Is there anything you'd like reviewers to focus on?**
Should be pretty …
> Chore: Use require-uncached to avoid stale cache in tests (fixes #44)

- plugin/templates/_package.json
Generated plugins will now use ESLint 3.x (specifically `~3.9.1`). This will help ensure that generated plugins with new-style rules won't run into problems.
> Update: Plugin package.json template devDependencies upgrade (fixes #52)

- package.json
The `run-async` package released version 2.3.0 recently, which completely dropped support for Node 0.10 by removing a Promise polyfill they were using internally. This has broken [our master build](https://travis-ci.org/eslint/generator-eslint/builds/181813236).
We should drop Node 0.10 support at some point, but I'd rather do that as a semver-major change. For now, this PR just adds a run-async dependency (pinning at 2.2.x) so that `npm install` will install the right version on Travis and keep this package working in Node 0.10 for now.
If we merge this, we can cut a minor release (when we're done with any other features we may want to add), and then drop Node 0.10 and Node 5 support in a semver-major release.
> Build: Pinning run-async dependency to 2.2.x

- rule/templates/_doc.md
Idea is that this will help core rule developers who use generator-eslint, and the language is pretty slick and generally applicable, but plugin rule authors can choose to change the text (like anything else in a Yeoman-generated scaffold).
> Update: Generated rule doc uses core ESLint example headers (fixes #21)

- package.json
This package was using the old-style metadata field. Updating to use just the SPDX string.
Assumption is we are using the MIT license (it sure looks like the MIT license, anyway). If I've got it wrong, let me know.
> Chore: Fix license field in package.json to be valid SPDX string

- plugin/templates/_package.json
The old template would generate a plugin project folder that contained vulnerable versions of mocha. This fix was attempted in #64 but wasn't merged because Travis was configured to support older versions of node.js. Looks like #68 dropped support for older versions of node.js and now we are safe to update these deps in the template.
> Chore: Updated the template devDependencies to fix vulnerabilities.

- plugin/templates/_package.json
Supporting the last 2-3 major ESLint versions should be sufficient and enables ESLint plugin developers to use newer ESLint features.
ESLint 6 released 2019-06
ESLint 7 released 2020-05
ESLint 8 coming soon
> Update: Add ESLint 6+ peer dependency to generated plugin template

- plugin/templates/_package.json
This is only affecting the generated plugin template so I'd argue it's not a breaking change like #81 is.
We now support Node 12, 14, 16+.
* Node 10 end-of-life 2021-04-30
* Node 13 end-of-life 2020-06-01
* Node 15 end-of-life 2021-06-01
https://nodejs.org/en/about/releases/
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md
https://en.wikipedia.org/wiki/Node.js#Releases
> Update: Drop Node 10 from generated plugin template

- .eslintrc.js
- .eslintrc.yml
- app/index.js
- lib/validators.js
- package-lock.json
- package.json
- plugin/index.js
- plugin/templates/_plugin.js
- rule/index.js
- tests/.eslintrc.yml
- tests/app/index.js
- tests/lib/validators.js
- tests/plugin/index.js
- tests/rule/index.js
- tests/test-load.js
Also switches to a flat/consolidated .eslintrc.js file.
Part of #86.
> Chore: Update and autofix internal linting

- README.md
Since we switched from Travis to GitHub Actions already.
> Docs: Fix CI build badge in README

- plugin/index.js
- plugin/templates/_.eslintrc.js
- plugin/templates/_package.json
Partially fixes #65.
We want to encourage the adoption of [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) to help ESLint plugin authors follow best practices including avoiding using deprecated APIs and producing rules with good usability.
I'll follow-up after this to add eslint-plugin-node and make some other improvements too.
> New: Add `eslint-plugin-eslint-plugin` to plugin generator

- plugin/templates/_.eslintrc.js
- plugin/templates/_package.json
Fixes #65.
We want to encourage plugin developers to use appropriate linting to help them produce high-quality plugins.
> New: Add `eslint-plugin-node` to plugin generator

- package-lock.json
- package.json
- plugin/index.js
> NodeJS version 10.12.0 has added a native support for both mkdir and mkdirSync to create a directory recursively with recursive: true option
https://stackoverflow.com/a/40686853
Part of #86.
> Chore: Remove unnecessary dependency `mkdirp`

- package-lock.json
- package.json
No references to it in the codebase.
Part of #86.
> Chore: Remove unused dependency `run-async`

- plugin/templates/_package.json
Avoid unnecessarily constraining the dependency versions which prevents users from receiving patch/minor updates.
> Fix: Use caret range for `requireindex` in template

- rule/templates/_rule.js
To encourage rule authors to fill in the rule type: https://eslint.org/docs/developer-guide/working-with-rules#rule-basics
Related: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-type.md
> Update: Add placeholder for `meta.type` in rule template

- rule/templates/_rule.js
To encourage rule authors to fill in the rule URL so that IDEs / code editors can provide a link to rule documentation on violations: https://eslint.org/docs/developer-guide/working-with-rules#rule-basics
Related: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-url.md
> Update: Add placeholder for `meta.docs.url` in rule template

- rule/index.js
Since it's more common for consumers to use this for generating ESLint plugin rules than ESLint core rules. We want the more common usage to be the default (first).
In this CLI prompt:
```
yo eslint:rule
? What is your name? John Doe
? Where will this rule be published? (Use arrow keys)
❯ ESLint Plugin
ESLint Core
```
> Update: Move `ESLint Plugin` before `ESLint Core` in CLI prompt

- .github/workflows/ci.yml
This ensures the lockfile is always up-to-date, among other benefits.
https://docs.npmjs.com/cli/v7/commands/npm-ci
> Chore: Use `npm ci` in CI workflow

- .github/workflows/ci.yml
- app/index.js
- package-lock.json
- package.json
- plugin/index.js
- rule/index.js
- tests/app/index.js
- tests/plugin/index.js
- tests/rule/index.js
Significantly modernizes code and tests.
Significantly improves test coverage.
TODO:
- `Uncaught Error: Cannot find module 'rimraf'`
- `Uncaught Error: Cannot find module 'mkdirp'`
- Recreating package-lock.json helped, but I was still seeing errors on Node 12/14 until I switched CI to use NPM v7 when installing dependencies. This is the same thing the yeoman-environment does on its [CI configuration](https://github.com/yeoman/environment/blob/main/.github/workflows/ci.yml#L41).
Fixes #43.
Fixes #86.
CC: @platinumazure
> Breaking: Upgrade yeoman dependencies to latest

- plugin/templates/_.eslintrc.js
- plugin/templates/_plugin.js
- rule/templates/_rule.js
- rule/templates/_test.js
Fixes #95.
Applies the default prettier formatting to all the template files. The goal is that a generated plugin/rule will be fully-ready (no violations) for anyone who wants to use prettier to lint their ESLint plugin.
> Update: Fix linting inconsistencies in templates

- package.json
Just to make sure we don't end up with unused ESLint disable directive comments ever.
https://eslint.org/docs/user-guide/command-line-interface#options
> Chore: Catch unused ESLint comments internally

- package.json
Make it easier to find this tool: https://eslint.org/docs/developer-guide/working-with-plugins#share-plugins
> Docs: Add `eslint` keyword in package.json

- rule/templates/_rule.js
There's no need for this to take up multiple lines.
> Docs: Switch to single-line comment for rule jsdoc type

- app/index.js
- package-lock.json
- plugin/index.js
- tests/app/index.js
- tests/lib/validators.js
- tests/plugin/index.js
- tests/rule/index.js
- tests/test-load.js
Delete the lockfile and recreate it.
This is generally a good thing to do every few months to pull in minor/patch version updates and removed duplicate versions/cruft. It only affects internal development.
A bug fix in eslint-plugin-node has resulted in us being able to remove some lint comments.
> chore: recreate package-lock.json

- .github/workflows/ci.yml
Add node v18 to test workflow.
> ci: add node v18 to test workflow

- rule/templates/_rule.js
Resolves #131 
There didn't seem to be any tests that broke from this change so I imagine it was more of a 'content' detail and we're safe to leave it without tests. Let me know if there's anything I missed!
> fix: remove unused meta.docs.category field in rule template

- plugin/templates/_package.json
ESLint v6 was released in [2019](https://eslint.org/blog/2019/06/eslint-v6.0.0-released/). Supporting the last two versions, ESLint v7 and ESLint v8, should be sufficient. ESLint v9 will also be released later this year.
> feat: drop ESLint v6 support in plugin template

- plugin/templates/_package.json
This follows the lead of ESLint core and other ESLint plugins in strictly defining their Node API so that users cannot reach in and import/depend on arbitrary files inside the plugin.
* https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#remove-lib
> Beginning in v8.0.0, ESLint is strictly defining its public API. Previously, you could reach into individual files such as require("eslint/lib/rules/semi") and this is no longer allowed. There are a limited number of existing APIs that are now available through the /use-at-your-own-risk entrypoint for backwards compatibility, but these APIs are not formally supported and may break or disappear at any point in time.
https://nodejs.org/api/packages.html#main-entry-point-export
> feat: strictly define Node API in plugin template

- plugin/templates/_package.json
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/releases/tag/v5.0.0
* https://github.com/mochajs/mocha/releases/tag/v10.0.0
Since these major version updates dropped Node 12 support, this PR depends on us also dropping Node 12 support:
* https://github.com/eslint/generator-eslint/pull/135
> feat: upgrade plugin template dependencies

- plugin/templates/_README.md
- plugin/templates/_package.json
- rule/templates/_doc.md
- tests/rule/index.js
[eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) is a CLI tool I built for automating the generation of the README rules list table and rule doc title/notices (e.g. auto-fixable, has suggestions, deprecated, etc) for ESLint plugins. It follows common documentation conventions from ESLint and top ESLint plugins and will help us standardize documentation across ESLint plugins (and generally improve the usability of custom rules through better documentation as well as streamline the process of adding new rules). It has 100% test coverage and is [used in many](https://github.com/bmish/eslint-doc-generator#users) of the top ESLint plugins already. 
The primary change in this PR is to install the new dev-dependency and add the following scripts to the plugin template …
> feat: add eslint-doc-generator to plugin template

- README.md
This basically helps anyone that has a lower version of node to know the requirement and at least have the minimum node version
> docs: add node version requirement to readme

- .github/workflows/release-please.yml
This configures the [release-please action][1] for `generator-eslint`. As we merge changes using [Conventional Commits formatting][2], release-please will create and update a pending release PR. That PR will contain a changelog of any commits merged since the prior release. When we're ready to do the release, we'll merge that PR, and the workflow in this PR will update the changelog and publish the release to GitHub and npm.
Separate from the code in this PR, I had to take a few manual steps:
1. Create a new [npm granular access token][3].
1. Name it ~~`release-please $package-name`~~ `release-please`.
1. Choose a reasonable expiration. I went with 365 days.
1. Under Packages and Scopes > select "Read and write" access > select ~~"Only select packages and scopes" > select the package that …
> chore: Set up release-please

- .github/workflows/release-please.yml
The default PR title is `chore${scope}: release${component} ${version}`, but our commit title bot doesn't expect scopes after the tag.
> ci: remove scope from release PR title

- .github/workflows/add-to-triage.yml
Adding pull requests to the triage board always fails due to wacky GitHub permissions, so removing it in order for pull request checks to come back clean.
> chore: Update add-to-triage.yml

- .github/workflows/ci.yml
This PR fixes the CI test jobs.
Currently, the jobs will attempt to install the latests version of npm regardless of the installed version of Node.js. This has been problematic since the release of npm 10, because npm 10 does not support all versions of Node.js that this package supports.
~The fix is to explicitly indicate which version of npm (currently 9 or 10) should be installed along with Node.js.~ Upgrading npm doesn't seem necessary, so removing that step will fix the build.
> ci: don't install latest npm

- plugin/templates/_README.md
Builds on top of the original PR to add [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator):
* https://github.com/eslint/generator-eslint/pull/140
Adds a placeholder section for configs, similar to the existing rules section below it, which can turn into something like this when running `npm run update:eslint-docs`:
|    | Name          | Description                                      |
| :- | :------------ | :----------------------------------------------- |
| ✅  | `recommended` | These rules are recommended for everyone.        |
| 🎨 | `stylistic`   | These rules are more about code style than bugs. |
| ⌨️ | `typescript`  | These are good rules to use with TypeScript.     |
This feature shipped in:
* https://github.com/bmish/eslint-doc-generator/releases/tag/v1.5.0
* …
> feat: add auto-generated configs list to readme in template

- package-lock.json
- package.json
This PR updates the eslint-release dev dependency to [v3.2.2](https://github.com/eslint/eslint-release/releases/tag/v3.2.2).
> chore: update dependency eslint-release to ^3.2.2

- rule/templates/_rule.js
- closes #181
After creating a plugin with `yo eslint:plugin`, then a rule with `yo eslint:rule`, executing linting with `npx eslint .` produces the following error and there is no related property for this in the skeleton rule which has been created.
> error  `meta.messages` must contain at least one violation message      eslint-plugin/prefer-message-ids
```js
messages: {}, // Add messageId and message
```
is added to [rule/templates/_rule.js](https://github.com/eslint/generator-eslint/blob/main/rule/templates/_rule.js)
- Rule [eslint-plugin/prefer-message-ids](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/prefer-message-ids.md)
- [MessageIds](https://eslint.org/docs/latest/extend/custom-rules#messageids)
> feat: add messages to rule template

- README.md
- PR https://github.com/eslint/generator-eslint/pull/169 bumped the Node.js requirements to
https://github.com/eslint/generator-eslint/blob/92a44afb6bb04bd7b247111aa9d0f2c2b07558b2/package.json#L53-L55
whilst [README > Installation](https://github.com/eslint/generator-eslint/blob/main/README.md#installation) was left unchanged stating
> **Requirements**
>
> - Node.js ^14.17.0 || ^16.0.0 || >= 18.0.0
[README > Installation](https://github.com/eslint/generator-eslint/blob/main/README.md#installation) is updated to read
> **Requirements**
>
> - Node.js ^18.18.0 || ^20.9.0 || >=21.1.0
in line with [package.json](https://github.com/eslint/generator-eslint/blob/main/package.json)
> docs: align readme node.js with package.json

- .gitignore
Adds `/.vscode/` to `.gitignore`.
Particularly useful at the moment since we're now using flat config for linting and `vscode-eslint` still needs to be configured with `"eslint.experimental.useFlatConfig": true`.
> chore: add `.vscode` to `.gitignore`

- plugin/templates/_package.json
Adds `"files": [ "lib" ]` to the generated `package.json`.
To avoid lint errors:
```
C:\projects\tmp\tmp\eslint.config.mjs
1:22  error  "@eslint/js" is not published                   n/no-unpublished-import
2:24  error  "eslint-plugin-n" is not published              n/no-unpublished-import
3:26  error  "eslint-plugin-eslint-plugin" is not published  n/no-unpublished-import
```
And I believe the plugin author would anyway have to add it before publishing.
> feat: add `"files"` to generated `package.json`

- rule/templates/_test.js
Since the lint config (`eslint-plugin-eslint-plugin` in particular) is set to enforce the use of messageId's in rules, I think it makes more sense for the test example to use `messageId` instead of `message`.
> feat: use `messageId` in tests

- plugin/templates/_README.md
- tests/plugin/index.js
- closes https://github.com/eslint/generator-eslint/issues/193
- PR https://github.com/eslint/generator-eslint/pull/179 converted templates to ESLint `v9` omitting to update [plugin/templates/_README.md](https://github.com/eslint/generator-eslint/blob/main/plugin/templates/_README.md). A `README.md` document generated with `generator-eslint@5.1.0` incorrectly refers to configuring an `.eslintrc` configuration file instead of describing how to configure a [current configuration file](https://eslint.org/docs/latest/use/configure/configuration-files).
- The [plugin/templates/_README.md](https://github.com/eslint/generator-eslint/blob/main/plugin/templates/_README.md) `Usage` section is converted from legacy to flat configuration and aligned to the current [Configure …
> fix: convert README template usage to flat

- plugin/templates/_package.json
https://github.com/bmish/eslint-doc-generator/releases/tag/v2.0.0
No major changes besides modernizing the requirements.
> chore: use eslint-doc-generator v2 in plugin template

- package.json
- plugin/templates/_package.json
Not really a fix but it is external-facing since the plugin template is updated.
* https://github.com/mochajs/mocha/releases/tag/v11.0.0
This will also enable us to trigger a release with:
* https://github.com/eslint/generator-eslint/pull/197
> fix: update to mocha v11

- plugin/templates/_eslint.config.mjs
when running `npx eslint .`, it output the errors:
```bash
Oops! Something went wrong! :(
ESLint: 9.37.0
TypeError: Plugin config "mixed-esm-and-cjs" not found in plugin "n".
at findPluginConfig (/tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index.cjs:287:8)
at /tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index.cjs:423:25
at Array.map (<anonymous>)
at processExtends (/tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index.cjs:421:36)
at /tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index.cjs:497:38
at Array.flatMap (<anonymous>)
at processConfigList (/tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index.cjs:497:20)
at defineConfig (/tmp/tmp.6CcU4BUgW5/node_modules/@eslint/config-helpers/dist/cjs/index …
```
> fix: eslint config error when using defineConfig
