eslint/generator-eslint

README.md, plugin/index.js, plugin/templates/_README.md, plugin/templates/_package.json, plugin/templates/_plugin.js, rule/templates/_test.js, test/test-creation.js
=> Plugin Generator

lib/validators.js, plugin/index.js, rule/index.js, test/test-validation.js
- pulled out the validators to their own file, and use the same regex for plugin id and rule id
- added tests
=> Fix: fix rule id and plugin id validator (fixes #11)

.eslintignore, .eslintrc, package.json, plugin/index.js, rule/index.js, test/test-creation.js, test/test-load.js, test/test-validation.js
Added linting with ESLint and fixed the resulting rule violations. All template files are ignored because they cause parse errors.
=> Build: Lint generator-eslint with eslint (fixes #26)

plugin/templates/_package.json
Adds mocha as a dependency in the package.json template.
=> Fix: add mocha as a dependency (fixes #32)

rule/templates/_rule.js
**What issue does this pull request address?**
Fixes #36.
**What changes did you make? (Give an overview)**
Changed the structure of the _rule.js template to conform to ESLint's new rule format.
**Is there anything you'd like reviewers to focus on?**
I did run eslint on the generated file and everything looks good (it at least parses), but it would be good to get a second set of eyes on it. You can use `npm link` to link the branch to a global pseudo-install of generator-eslint, and then `yo eslint:rule` lets you run the new code.
Also, should I write any new tests for this?
=> Update: Rule generator uses new rule format (fixes #36)

package.json
This ensures that future releases of generator-eslint will automatically push to GitHub.
=> Upgrade: eslint-release@^0.10.1

README.md
I've never used Yeoman before, so this was initially confusing to me when I tried to use this generator.
=> Docs: clarify that Yeoman needs to be installed separately

.travis.yml
Might as well add this since it's on Active LTS.
=> Build: Test in Node 6 (and 7) on Travis

appveyor.yml
=> Build: Add appveyor.yml, testing against Node 7

README.md
This PR changes the build badges to SVG for sharper readability ✨
=> Chore: Use SVG badge in README for readability

plugin/templates/_package.json
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#900--2021-06-07
=> Update: Bump mocha to v9 in generated plugin template

package-lock.json, package.json, tests/app/index.js
`spy.reset() is removed, use spy.resetHistory()`: https://sinonjs.org/guides/migrating-to-5.0.html
Part of #86.
=> Chore: Update testing dependencies to latest

package-lock.json, package.json
https://github.com/eslint/eslint-release/releases/tag/v3.0.0
https://github.com/eslint/eslint-release/releases/tag/v2.0.0
Part of #86.
=> Chore: Update `eslint-release` to v3

package-lock.json, package.json, tests/plugin/index.js, tests/rule/index.js
require-uncached renamed to import-fresh: https://github.com/sindresorhus/import-fresh/releases/tag/v3.0.0
https://www.npmjs.com/package/require-uncached
Part of #86.
=> Chore: Replace deprecated `require-uncached` with `import-fresh`

.github/workflows/ci.yml
Tests were not running since it looks like the branch was renamed.
=> Chore: Fix CI to run on correct branch

.editorconfig, README.md, plugin/templates/_README.md
All of these sites now use HTTPS.
=> Docs: Switch to HTTPS links

rule/templates/_rule.js
* Conciseness
* More clear comment explanation
=> Update: Tweak `schema` property formatting in rule template

package.json
The description that shows up when you search for this package on NPM is not helpful today: https://www.npmjs.com/search?q=generator-eslint
=> Docs: Add better description in package.json

.github/workflows/release-please.yml
Updates release-please configuration so that all commits will be included in changelogs.
Same as https://github.com/eslint/create-config/pull/57
=> chore: include all commits in the changelog

.github/workflows/ci.yml
Adds Node.js 22 to the test matrix.
=> ci: Test in Node.js 22

eslint.config.js, package.json
Switches to eslint-config-eslint v11.
=> chore: switch to eslint-config-eslint v11

.github/workflows/ci.yml, package.json
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
CI
Add Node.js v23 environment
No
No
=> ci: add Node.js v23
